### ISSUE TITLE
Support Tables in foldPretty (now that elm-markdown parses table)

### ISSUE THREAD

**Issue by alltonp** [matheus23/elm-markdown-transforms#3]
Hi,

I'd really like to use your library, would it be possible to have foldPretty support Tables?

The latest elm-markdown is now able to parse them...

Many thanks,
Paul

**Comment by matheus23** [comment]
I'll update the library :+1:

**Comment by matheus23** [comment]
I've added support for this.
Check out the accompanying example: https://elm-markdown-transforms.netlify.app/format-tables.html

Check out the example source code (Linked on the above site) and the accompanying documentation: https://package.elm-lang.org/packages/matheus23/elm-markdown-transforms/latest/Markdown-AnchorValidation

Let me know if this solves your usecase (and re-open the issue then) :+1:

**Comment by alltonp** [comment]
Thank you the superfast turnaround!

This looks great based on the example, will try it out in my app and let you know

**Comment by alltonp** [comment]
Integrated with my app very easily and I was about to ask how to style the table and then discovered compact style. I have use case for both, so thank you for that.
