### ISSUE TITLE
Rendering a Table with no rows results in delimiter line being lost

### ISSUE THREAD

**Issue by alltonp** [matheus23/elm-markdown-transforms#4]
Hi,

If you render a `Table` with no rows the delimiter line gets lost on rendering, which means if you parse it again then it becomes a `Paragraph`.

e.g.

When `elm-markdown` parses the following:
```
one | two
--- | ---
```

it is correctly parsed as a `Table` block

However when `elm-markdown-transforms` renders it, it becomes:

```
one | two
```

When `elm-markdown` parses it the next time it becomes a `Paragraph` instead of a `Table`

This doesn't seem right and breaks my application.

According to this spec, a table with no rows is valid markdown:
https://github.github.com/gfm/#tables-extension- (see example 205)

**Comment by matheus23** [comment]
Good find.

* Added a regression test
* I've published a patch release (3.0.1)

Let me know if that works for you.

**Comment by alltonp** [comment]
Thank you for the quick response again!

That is looking great, just one small thing... If you have a Paragraph after the Table (with no rows), when it is rendered an extra blank row is being inserted, is it possible tow remove that? It works as expected when there are rows.

Sorry if this seems a bit picky, but I'm round-tripping moving data between tables and it looks very odd when extra rows appear/disappear.

e.g. empty rows produces
```
one | two
--- | ---


para after table
```

should be:
```
one | two
--- | ---

para after table
```

**Comment by matheus23** [comment]
> Sorry if this seems a bit picky, but I'm round-tripping moving data between tables and it looks very odd when extra rows appear/disappear.

That is absolutely fine. My goal for the pretty-printer is for it to be round-trippable and idempotent. I'm also trying to ensure this via tests, but haven't had much time to gather lots of test data/write a markdown fuzzer.

You can see these properties tested here:
https://github.com/matheus23/elm-markdown-transforms/blob/df47860dfac7488f750a129a617c5cee6dc56d5c/tests/Tests.elm#L29-L77

And e.g. some of the test data used is here:
https://github.com/matheus23/elm-markdown-transforms/blob/df47860dfac7488f750a129a617c5cee6dc56d5c/tests/Tests.elm#L270-L290

The data doesn't cover this case right now. I'll add a regression test and fix it.

**Comment by matheus23** [comment]
Actually, I'm not sure what exactly your issue is. I've added your example to the tests, and it round-trips and idempotency test just fine.

I've also just copy-pased your example into the online example website (https://elm-markdown-transforms.netlify.app/format-tables.html), and it produces just what you describe as "should be":
![image](https://user-images.githubusercontent.com/1430958/105029859-30a77b80-5a53-11eb-8dad-69b424752c12.png)

Please reopen this issue if there's a case I've missed :)

Maybe your case is a special case for when you're generating the markdown by yourself from elm rather than obtaining a markdown AST from parsing?

**Comment by matheus23** [comment]
*sigh*, I checked again, I just missed the newline (barely visible in the screenshot). It *is* there.

I added a regression test:
https://github.com/matheus23/elm-markdown-transforms/blob/e6419b4c32156e633eb03115bff120e1b24f9797/tests/Tests.elm#L51-L67

And a fix.

Let me know if that works for you :)

**Comment by alltonp** [comment]
Thank you, that's all fixed now.

Pleased to hear about your round-trips and idempotency. I'm doing the same, parsing to a markdown AST, then transforming the AST before rendering it with your library. It's working nicely now. I wonder if another library of AST transformations might emerge out of it.

Cheers,
Paul
